server.port=8091
#spring.data.mongodb.database=productdb
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root
spring.data.mongodb.uri="mongodb+srv://wearestarting2018:HBeO2YgABqE31Np2@tindibackend.w01vw.mongodb.net/?retryWrites=true&w=majority&appName=TindiBackend";